// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: article.sql

package db

import (
	"context"
)

const getAllArticle = `-- name: GetAllArticle :many
select id, create_at, user_id, username, title, favoritenum, commentnum, watchnum
from article
`

func (q *Queries) GetAllArticle(ctx context.Context) ([]*Article, error) {
	rows, err := q.db.QueryContext(ctx, getAllArticle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.CreateAt,
			&i.UserID,
			&i.Username,
			&i.Title,
			&i.Favoritenum,
			&i.Commentnum,
			&i.Watchnum,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
