// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
	"time"
)

type Article struct {
	ID          int32     `json:"id"`
	CreateAt    time.Time `json:"create_at"`
	UserID      int32     `json:"user_id"`
	Username    string    `json:"username"`
	Title       string    `json:"title"`
	Favoritenum int32     `json:"favoritenum"`
	Commentnum  int32     `json:"commentnum"`
	Watchnum    int32     `json:"watchnum"`
}

type Comment struct {
	ID          int32     `json:"id"`
	CreatedAt   time.Time `json:"created_at"`
	Favoritenum int32     `json:"favoritenum"`
	UserID      int32     `json:"user_id"`
	Username    string    `json:"username"`
	ArticleID   int32     `json:"article_id"`
	Content     string    `json:"content"`
	// 为0时为顶级评论
	ParentID int32 `json:"parent_id"`
}

type Divide struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	Nickname string `json:"nickname"`
	Describe string `json:"describe"`
	// 为0时为顶级标签
	ParentID int32 `json:"parent_id"`
}

type Tag struct {
	ID        int32  `json:"id"`
	ArticleID int32  `json:"article_id"`
	TagName   string `json:"tag_name"`
}

type User struct {
	ID          int32          `json:"id"`
	Username    string         `json:"username"`
	Password    string         `json:"password"`
	Email       string         `json:"email"`
	Avatar      sql.NullString `json:"avatar"`
	CreateAt    time.Time      `json:"create_at"`
	Age         sql.NullInt32  `json:"age"`
	PhoneNumber sql.NullString `json:"phone_number"`
	Sign        sql.NullString `json:"sign"`
}
