// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	GetAllArticle(ctx context.Context) ([]*Article, error)
	GetAllTag(ctx context.Context) ([]*Tag, error)
}

var _ Querier = (*Queries)(nil)
